############# German navigation ##############

# main menu
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Über"
url = "/about"
weight = 2

[[main]]
name = "Studenten"
url = "/students"
weight = 3

[[main]]
name = "Blog"
url = "/de/blog"
weight = 4

[[main]]
name = "Kontakt"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "Über"
url = "/about"
weight = 1

[[footer]]
name = "Studenten"
url = "/students"
weight = 2

[[footer]]
name = "Blog"
url = "/de/blog"
weight = 3

[[footer]]
name = "Kontakt"
url = "/contact"
weight = 4

[[footer]]
name = "Admin"
url = "/admin/"
weight = 5
