############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Students"
url = "/de/students"
weight = 3

[[main]]
name = "Blog"
url = "/de/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Students"
url = "/de/students"
weight = 2

[[footer]]
name = "Blog"
url = "/de/blog"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Admin"
url = "/admin/"
weight = 5
