############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "/about"
weight = 2

[[main]]
name = "Étudiants"
url = "https://romainaubry.pages.dev/de/students"
weight = 3

[[main]]
name = "Blog"
url = "https://romainaubry.pages.dev/de/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "À propos"
url = "/about"
weight = 1

[[footer]]
name = "Étudiants"
url = "https://romainaubry.pages.dev/de/students"
weight = 2

[[footer]]
name = "Blog"
url = "https://romainaubry.pages.dev/de/blog"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Admin"
url = "/admin/"
weight = 5
